pwm:
	iverilog -o pwm pwm.v pwm_run.v
run:
	vvp pwm

# robot:
# 	iverilog -o robot ./real-fpga-robot/pwm.v ./real-fpga-robot/realfpgarobot.v


# run-robot:
# 	vvp robot

# drivecontrol:
# 	iverilog -o drivecontrol ./drive-control/control.v ./drive-control/pwml.v ./drive-control/drive-control.v

# run-drivecontrol:
# 	vvp drivecontrol

# driver:
# 	iverilog -o driver ./drive/control.v ./drive/pwm.v ./drive/drive.v ./drive/clock.v

# run-driver:
# 	vvp driver

# clean:
# 	rm pwm robot drivecontrol driver
